#$Id: makefile.old 185 2011-08-29 04:30:16Z ccfeng $

DEBUG = 
CFLAGS= $(DEBUG)

FORTRAN = ifort 
FFLAGS  = $(DEBUG) -O3 -module $(BINFOLD) 
F90FLAGS= $(DEBUG)

CC	= icc -O3
CFLAGS  = -O3 $(DEBUG)

LINKER  = ifort 
LINKFLAGS = $(DEBUG) -O3 -nofor_main

BINFOLD = ../bin
LIBSFOLD= ../libs

include ../libs/source.mk
vpath %.o $(BINFOLD)/
vpath %.mod $(BINFOLD)/

TEST_SRC = \
	 tlaplace_coefficient.o  
	 #companion_force.o \
	 #smooth_func.o \
	 #bar_force.o \
	 #plot_rotation.o 

TEST_OBJ= $(addprefix ./,$(TEST_SRC))
TEST_BIN= $(subst .o,.exe,$(TEST_SRC))
LIBS_OBJ= $(addprefix $(BINFOLD)/,$(LIBS_SRC))

OBJECT  = $(LIBS_OBJ) $(TEST_OBJ)

# 64bit matlab lib
LIB = -L/penguin/apps/matlabR14/bin/glnxa64 -lmat -lmx -L$(LAMHOME)/lib -lmpi -llam
MKLROOT=/opt/intel/mkl/10.0.1.014/lib/em64t

.SUFFIXES:.exe .f .c .o 
.PHONY: check_libs

all:    check_libs $(TEST_BIN)

check_libs: $(BINFOLD)/$(LIBS_SRC)
	cd $(LIBSFOLD);$(MAKE)

%.exe:  %.o $(BINFOLD)/libn4622.a 
	$(FORTRAN) $< -o $@ -I$(BINFOLD) \
	-module $(BINFOLD) -L$(BINFOLD) -ln4622 \
	-lpgplot  \
	$(GSL_INCL) $(GSL_LIBS) -lgsl -lgslcblas \
	-I$(MATLABROOT)/extern/include $(LIB) \
	-lpthread -openmp \
	-L$(BINFOLD) -lslatec

%.o:	 %.f
	$(FORTRAN) -c $< -o $@ -I$(BINFOLD) -openmp

$(BINFOLD)/%.o:
	cd $(LIBSFOLD);$(MAKE)
	
clean :
	@rm ../bin/*.o;rm -rf *.exe *.o
